spring.application.name=social-media-backend
#spring.datasource.url=jdbc:mysql://root:BQJEyZWppzzPopGFaewbRtpWpBiQTioy@mysql.railway.internal:3306/railway
#spring.datasource.username=root
#spring.datasource.password=BQJEyZWppzzPopGFaewbRtpWpBiQTioy
#spring.datasource.url=jdbc:mysql://thomas.proxy.rlwy.net:52209/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=BQJEyZWppzzPopGFaewbRtpWpBiQTioy
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =======================
# DATABASE (RAILWAY MYSQL)
# =======================
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=true&&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =======================
# JPA / HIBERNATE
# =======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
server.port=${PORT:8080}


# =======================
# CLOUDINARY (OPTIONAL - use env vars in code)
# =======================
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}